# src/tools/pdf_export.py

import os
from fpdf import FPDF
from datetime import datetime


def _clean_text(text: str) -> str:
    """
    Removes or replaces ALL characters that Helvetica cannot handle.
    Helvetica only supports basic Latin characters (ASCII range).
    Any symbol outside that range must be replaced here.
    """
    if not isinstance(text, str):
        text = str(text)

    replacements = {
        # Currency symbols
        "\u20b9": "Rs.",   # ₹ Indian Rupee
        "\u20ac": "EUR",   # € Euro
        "\u00a3": "GBP",   # £ Pound
        "\u00a5": "JPY",   # ¥ Yen
        "\u0024": "$",     # $ Dollar (safe but included)

        # Quotes and dashes
        "\u2019": "'",     # Right single quote
        "\u2018": "'",     # Left single quote
        "\u201c": '"',     # Left double quote
        "\u201d": '"',     # Right double quote
        "\u2013": "-",     # En dash
        "\u2014": "-",     # Em dash
        "\u2015": "-",     # Horizontal bar

        # Bullets and symbols
        "\u2022": "*",     # Bullet point
        "\u25cf": "*",     # Filled circle
        "\u25ba": ">",     # Arrow
        "\u2713": "OK",    # Checkmark
        "\u2714": "OK",    # Heavy checkmark
        "\u2718": "X",     # Cross mark
        "\u2026": "...",   # Ellipsis
        "\u00b7": "*",     # Middle dot

        # Math and misc
        "\u00d7": "x",     # Multiplication sign
        "\u00f7": "/",     # Division sign
        "\u00b0": " deg",  # Degree symbol
        "\u00ae": "(R)",   # Registered trademark
        "\u00a9": "(C)",   # Copyright
        "\u2122": "(TM)",  # Trademark

        # Indian language/misc unicode that Groq sometimes outputs
        "\u00a0": " ",     # Non-breaking space → regular space
    }

    for original, replacement in replacements.items():
        text = text.replace(original, replacement)

    # Final safety net: remove any remaining non-ASCII characters
    # encode to ASCII, ignore failures, decode back to string
    text = text.encode("ascii", errors="ignore").decode("ascii")

    return text


class ReportPDF(FPDF):
    """
    Custom PDF class with header and footer on every page.
    Uses only Helvetica — no external font files needed.
    """

    def __init__(self, company_name: str):
        super().__init__()
        # Store cleaned company name for header use
        self.company_name = _clean_text(company_name)

    def header(self):
        # Dark blue background bar
        self.set_fill_color(30, 58, 138)
        self.rect(0, 0, 210, 18, style="F")

        # White bold text on blue bar
        self.set_font("Helvetica", style="B", size=11)
        self.set_text_color(255, 255, 255)
        self.set_y(5)
        self.cell(
            0, 8,
            f"  Company Intelligence Report: {self.company_name}",
            align="L"
        )

        self.ln(16)
        self.set_text_color(0, 0, 0)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", style="I", size=8)
        self.set_text_color(128, 128, 128)
        self.cell(
            0, 10,
            f"Page {self.page_no()}  |  Generated by AI Research Agent  |  {datetime.now().strftime('%d %b %Y')}",
            align="C"
        )


def _add_section(pdf: ReportPDF, title: str, content: str, color: tuple):
    """
    Adds one report section with colored title and body text.
    """
    # Section title
    pdf.set_font("Helvetica", style="B", size=13)
    pdf.set_text_color(*color)
    pdf.cell(0, 8, _clean_text(title), ln=True)
    pdf.ln(2)

    # Colored underline
    pdf.set_draw_color(*color)
    pdf.set_line_width(0.5)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)

    # Body content
    pdf.set_font("Helvetica", size=10)
    pdf.set_text_color(40, 40, 40)
    pdf.multi_cell(0, 6, _clean_text(content))
    pdf.ln(8)


def export_to_pdf(report: dict, company_name: str) -> str:
    """
    Converts report dictionary into a formatted PDF.
    Returns the file path of the saved PDF.
    """

    pdf = ReportPDF(company_name=company_name)
    pdf.set_margins(left=10, top=10, right=10)
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Company name as large title
    pdf.set_font("Helvetica", style="B", size=20)
    pdf.set_text_color(30, 58, 138)
    pdf.ln(4)
    pdf.cell(0, 12, _clean_text(company_name), ln=True, align="C")

    # Date subtitle
    pdf.set_font("Helvetica", size=11)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(
        0, 7,
        f"Intelligence Report  |  {datetime.now().strftime('%d %B %Y')}",
        ln=True,
        align="C"
    )
    pdf.ln(8)

    # Divider line
    pdf.set_draw_color(30, 58, 138)
    pdf.set_line_width(1)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(10)

    # All 5 sections
    sections = [
        (
            "1.  Company Overview",
            report.get("overview", "Not available"),
            (30, 58, 138)
        ),
        (
            "2.  Key Business Information",
            report.get("business_info", "Not available"),
            (5, 120, 85)
        ),
        (
            "3.  Potential Business Challenges",
            report.get("challenges", "Not available"),
            (180, 60, 30)
        ),
        (
            "4.  AI Opportunities",
            report.get("ai_opportunities", "Not available"),
            (80, 30, 160)
        ),
        (
            "5.  Personalized CEO Pitch",
            report.get("pitch", "Not available"),
            (10, 100, 150)
        ),
    ]

    for title, content, color in sections:
        _add_section(pdf, title, content, color)

    # Save to outputs/
    os.makedirs("outputs", exist_ok=True)
    safe_name = company_name.strip().replace(" ", "_").lower()
    safe_name = safe_name.encode("ascii", errors="ignore").decode("ascii")
    file_path = os.path.join("outputs", f"{safe_name}_report.pdf")

    pdf.output(file_path)
    print(f"PDF saved to: {file_path}")

    return file_path


# Independent test
if __name__ == "__main__":
    test_report = {
        "overview": (
            "Adani Realty is the real estate division of the Adani Group. "
            "The company has invested Rs. 10,000 crore in Mumbai projects. "
            "Operations span residential and commercial segments."
        ),
        "business_info": (
            "Major projects include Dharavi redevelopment worth Rs. 20,000 crore. "
            "Recent expansion into affordable housing in Tier-2 cities."
        ),
        "challenges": (
            "1. Regulatory complexity across multiple states.\n"
            "2. Construction cost inflation of 18% year-on-year.\n"
            "3. Slowing sales velocity in premium segment."
        ),
        "ai_opportunities": (
            "1. NLP for RERA document compliance automation.\n"
            "2. Predictive pricing using satellite and market data.\n"
            "3. Lead scoring for sales teams."
        ),
        "pitch": (
            "Dear Mr. Adani,\n\n"
            "I am reaching out regarding AI opportunities at Adani Realty. "
            "Our analysis identifies three high-impact areas where AI can "
            "directly improve your operational efficiency and sales outcomes."
        )
    }

    path = export_to_pdf(test_report, "Adani Realty")
    print(f"Test complete. Open: {path}")